name: build

on:
  push:
    branches:
      - theme
  workflow_dispatch:

env:
  BUILD_SH: build_release.sh

jobs:
  Build:
    name: "Release"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container: devkitpro/devkita64

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 'Get REPO Name'
      run: |
        echo "REPO=$(echo $GITHUB_REPOSITORY | sed 's/WE1ZARD\///')" >> $GITHUB_ENV

    - name: 'Get Version'
      run: |
        echo "version=$(sed -n 1p ./update_log.md | sed "s/##\s//")" >> $GITHUB_ENV

    - name: 'Set Version'
      run: |
        sed -i "s/{beta}/${{ env.version }}/g" ./sphaira/CMakeLists.txt

    - name: 'Build'
      run: |
        chmod +x $BUILD_SH
        ./$BUILD_SH

    - name: 'Publish to target repository'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_name: wei2ard/AutoFetch
        repo_token: ${{ secrets.TOKEN }}
        file: ./out/sphaira.zip
        tag: latest
        overwrite: true
        prerelease: false